### PR TITLE
tagger: get the list of images from the channel's JSON [#121496825]

### PR DESCRIPTION
**Pull request by kdomanski**

### CODE REVIEW

**Comment by hinnerk** [comment]
I just used this to release the new RC. Can we merge it now? @kdomanski

**Comment by kdomanski** [comment]
I'm considering taking the image list from the source channel instead of destination.

**Comment by hinnerk** [comment]
Yes, please!

**Comment by hinnerk** [comment]
Used it again for RC 2. Seems okay-ish to me. @kdomanski

**Comment by hinnerk** [comment]
Looks good. Only it appears to me that the readme is outdated.

**Pull request merged**
